apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.name-web" . }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jitsi-meet.name-web" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jitsi-meet.name-web" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "jitsi-meet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "jitsi-meet.name-web" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          env:
            - name: XMPP_SERVER
              value: {{ include "jitsi-meet.name-prosody" . }}
            {{- if .Values.jicofo.userAuth.enabled }}
            - name: JICOFO_AUTH_USER
              value: {{ .Values.jicofo.userAuth.name }}
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "jitsi-meet.name-jicofo-config" . }}
                  key: JICOFO_AUTH_PASSWORD
            {{- end }}
            {{- if .Values.jvb.userAuth.enabled }}
            - name: JVB_AUTH_USER
              value: {{ .Values.jvb.userAuth.name }}
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "jitsi-meet.name-jvb-config" . }}
                  key: JVB_AUTH_PASSWORD
            {{- end }}
            {{- if .Values.prosody.auth.enabled }}
            - name: ENABLE_AUTH
              value: "1"
            - name: ENABLE_GUESTS
              value: {{ .Values.prosody.auth.guest | quote }}
            {{- end }}
            - name: XMPP_BOSH_URL_BASE
              value: "http://{{ include "jitsi-meet.name-prosody" . }}:5280"
            {{- range .Values.web.environment }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.common.environment }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
