# Default values for jitsi-meet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullSecrets: []

webHost: jitsi.meet.local

web:
  image:
    repository: jitsi/web
    tag: latest
    pullPolicy: Always
  environment:
    - name: ENABLE_LETSENCRYPT
      value: false
  replicaCount: 1
  jwtsidecar:
    extraArgs: {}
    resources: {}
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    metrics:
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70
  service:
    annotations: []
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    annotations: []
    hosts:
      - host: jitsi.meet.local
        oauth: false
        paths: []
    tls: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

jibri:
  image:
    repository: jitsi/jibri
    tag: latest
    pullPolicy: Always
  environment: []
  resources: {}

prosody:
  auth:
    enabled: true
    guest: 0
    type: internal
  image:
    repository: jitsi/prosody
    tag: latest
    pullPolicy: Always
  environment: []
  replicaCount: 1
  service:
    annotations: []
    type: ClusterIP
    portC2S1: 5222
    portC2S2: 5322
    sessionAffinityConfig:
      clientIPConfig:
        timeoutSeconds: 10800 # 3 hours
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: memory
          targetAverageUtilization: 70
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 70
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  recorder: false

jicofo: # jicofo is used as a sidecar container for every prosody instance
  image:
    repository: jitsi/jicofo
    tag: latest
    pullPolicy: Always
  environment: []
  componentSecret: ""
  userAuth:
    enabled: false
    name: "focus"
    secret: ""
  resources: {}

jvb:
  image:
    repository: jitsi/jvb
    tag: latest
    pullPolicy: Always
  environment: []
  replicaCount: 1
  securityContext:
    fsGroup: 412
  podSecurityContext:
    capabilities:
      add:
        - SYS_RESOURCE
        - NET_ADMIN
  service:
    annotations: []
    type: NodePort
    externalTrafficPolicy: Cluster
    sessionAffinity: None
  ingress:
    enabled: false
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  userAuth:
    enabled: false
    name: "jvb"
    secret: ""

ingressControllerNamespace: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

